---
name: First Workflow

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  validate-ami-template:
    runs-on: ubuntu-latest

    steps:
    - name: first step
      run: echo "Hello World!"
