name: Run packer build on AWS

on:
  pull_request:
    branches:
        - 'master'
  workflow_dispatch:
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Repository
         uses: actions/checkout@v2

       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
          # if you have/need it
          aws-region: us-east-1
       - name: Initialize Packer Template
         uses: hashicorp/packer-github-actions@master
         with:
           command: init

      # validate templates
       - name: Validate Template
         uses: hashicorp/packer-github-actions@master
         with:
           command: validate
           arguments: -syntax-only
           target: ami.pkr.hcl

       - name: Build Artifact
         uses: hashicorp/packer-github-actions@master
         with:
           command: build
           arguments: "-color=false -on-error=abort"
           target: ami.pkr.hcl
         env:
           PACKER_LOG: 1
