name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1qazwsx
          MYSQL_DATABASE: sys
        ports:
            - '8888:3306'
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo /etc/init.d/mysql start
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          mysql -h 0.0.0.0 --port 8888 -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS sys;'
      - name: test
        run: |
          pytest -q Test.py
