name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1qaz2wsx
          MYSQL_DATABASE: sys
        ports:
            - '3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          mysql -h 0.0.0.0 --port 3306 -u root -p1qaz2wsx -e 'CREATE DATABASE IF NOT EXISTS sys;'
          sudo /etc/init.d/mysql start
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: test
        run: |
          pytest -q Test.py
